spring:
  application:
    name: SpringCrudDemoApplication
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userDb
    username: root
    password: ammu
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update


server:
  port: 9191
